### ISSUE TITLE
VFS memdb URI's don't seem to work

### ISSUE THREAD

**Issue by dspinellis** [rogerbinns/apsw#553]
Specifying a `memdb` VFS URI in a `Connection` string [exactly as documented](https://rogerbinns.github.io/apsw/tips.html#memory-databases) or when attaching a `memdb` database URI, doesn't seem to work.

# Connection problem
In the `Connection` case the URI is partly recognized but its `vfs=memdb` arguments seems to be ignored.

## Example program
```py
import apsw
import apsw.bestpractice

apsw.bestpractice.library_logging()
conn1 = apsw.Connection("file:/shared&vfs=memdb", flags=apsw.SQLITE_OPEN_URI | apsw.SQLITE_OPEN_READWRITE)
```

## Execution results
```
$ python example.py
ERROR:root:SQLITE_LOG: cannot open file at line 44906 of [d2fe6b05f3] (14) SQLITE_CANTOPEN
ERROR:root:SQLITE_LOG: os_unix.c:44906: (0) open(/shared&vfs=memdb) - Success (14) SQLITE_CANTOPEN
Traceback (most recent call last):
  File "/home/dds/tmp/try/example.py", line 8, in <module>
    conn1 = apsw.Connection("file:/shared&vfs=memdb", flags=apsw.SQLITE_OPEN_URI | apsw.SQLITE_OPEN_READWRITE)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
apsw.CantOpenError: unable to open database file
```

It seems that *SQLite* is trying to create a file.
```
$ strace -e openat python example.py
[…]
openat(AT_FDCWD, "/shared&vfs=memdb", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/shared&vfs=memdb", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

# ATTACH problem
Attaching a `VFS` `memdb` database also fails: the URI isn't recognized at all.

## Example program
```py
import apsw
import apsw.bestpractice

apsw.bestpractice.library_logging()
conn1 = apsw.Connection("file:/shared", flags=apsw.SQLITE_OPEN_URI | apsw.SQLITE_OPEN_READWRITE, vfs="memdb")
conn2 = apsw.Connection(":memory:")  # Create a new separate connection
conn2.execute("ATTACH DATABASE 'file:/shared?vfs=memdb' AS shared_db")
```

## Execution results
```
$ python example.py
apsw.sqlite_lib_version()='3.48.0'
apsw.sqlite3_sourceid()='2025-01-14 11:05:00 d2fe6b05f38d9d7cd78c5d252e99ac59f1aea071d669830c1ffe4e8966e84010'
ERROR:root:SQLITE_LOG: cannot open file at line 44906 of [d2fe6b05f3] (14) SQLITE_CANTOPEN
ERROR:root:SQLITE_LOG: os_unix.c:44906: (0) open(/home/dds/tmp/try/file:/shared?vfs=memdb) - Success (14) SQLITE_CANTOPEN
ERROR:root:SQLITE_LOG: statement aborts at 4: [ATTACH DATABASE 'file:/shared?vfs=memdb' AS shared_db] unable to open database: file:/shared?vfs=memdb (14) SQLITE_CANTOPEN
Traceback (most recent call last):
  File "/home/dds/tmp/try/example.py", line 19, in <module>
    conn2.execute("ATTACH DATABASE 'file:/shared?vfs=memdb' AS shared_db")
  File "src/cursor.c", line 172, in resetcursor
apsw.CantOpenError: unable to open database: file:/shared?vfs=memdb
```

# What works
Creating a shared in-memory database by passing the `vfs` flag to `Connection` runs without a failure.
```py
import apsw
apsw.Connection("file:/shared", flags=apsw.SQLITE_OPEN_URI | apsw.SQLITE_OPEN_READWRITE, vfs="memdb")
```
However, this doesn't help when a database needs to be attached.

# Execution environment
```
$ apsw --version
3.48.0

$ python --version
Python 3.11.2

apsw.sqlite_lib_version()='3.48.0'
apsw.sqlite3_sourceid()='2025-01-14 11:05:00 d2fe6b05f38d9d7cd78c5d252e99ac59f1aea071d669830c1ffe4e8966e84010'

Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
```

**Comment by rogerbinns** [comment]
Thank you for the detailed report.  The mistake in the text is the first URI parameter is preceded by `?` while the rest are preceded by `&`.  I've now fixed the text.  Changing the `&` to `?` in the name in your reproducer fixes it.

Out of curiosity why do you prefer URI style over keyword parameters?

**Comment by rogerbinns** [comment]
> Out of curiosity why do you prefer URI style over keyword parameters

You answered that - attaching databases.

**Comment by dspinellis** [comment]
Thank you for the ultra-fast response and also, thank you for _apsw_! The virtual tables I create through it are instrumental to the [Alexandria3k](https://github.com/dspinellis/alexandria3k) package, which supplies a library and a command-line tool providing efficient relational query access to the several very large scientific publication open data sets.

**Comment by dspinellis** [comment]
The `ATTACH` command still fails.

# Example code
```py
import apsw
import apsw.bestpractice

apsw.bestpractice.library_logging()

conn1 = apsw.Connection("file:/shared?vfs=memdb",
                        flags=apsw.SQLITE_OPEN_URI | apsw.SQLITE_OPEN_READWRITE)
conn1.execute("CREATE TABLE people (id INTEGER PRIMARY KEY, name TEXT)")
conn1.execute("INSERT INTO people (name) VALUES ('Alice')")
conn1.execute("INSERT INTO people (name) VALUES ('Bob')")

conn2 = apsw.Connection(":memory:")
conn2.execute("ATTACH DATABASE 'file:/shared?vfs=memdb' AS shared_db")

for row in conn2.execute("SELECT * FROM shared_db.people"):
    print(row)
```

# Result
```
$ python example.py
ERROR:root:SQLITE_LOG: cannot open file at line 44906 of [d2fe6b05f3] (14) SQLITE_CANTOPEN
ERROR:root:SQLITE_LOG: os_unix.c:44906: (0) open(/home/dds/tmp/try/file:/shared?vfs=memdb) - Success (14) SQLITE_CANTOPEN
ERROR:root:SQLITE_LOG: statement aborts at 4: [ATTACH DATABASE 'file:/shared?vfs=memdb' AS shared_db] unable to open database: file:/shared?vfs=memdb (14) SQLITE_CANTOPEN
Traceback (most recent call last):
  File "/home/dds/tmp/try/example.py", line 17, in <module>
    conn2.execute("ATTACH DATABASE 'file:/shared?vfs=memdb' AS shared_db")
  File "src/cursor.c", line 172, in resetcursor
apsw.CantOpenError: unable to open database: file:/shared?vfs=memdb
```

**Comment by rogerbinns** [comment]
The attach is failing because URI mode is not active, and there is no way to specify it in the ATTACH statement.  You need to enable [URI mode](https://www.sqlite.org/c3ref/c_config_covering_index_scan.html#:~:text=must%20be%20threadsafe.-,SQLITE_CONFIG_URI,-The%20SQLITE_CONFIG_URI%20option) for SQLite as a whole.  It must be done first thing before any other SQLite operation.

    apsw.config(apsw.SQLITE_CONFIG_URI, 1)

It is a SQLite constraint - [Most of the configuration options for sqlite3_config() will only work if invoked prior to sqlite3_initialize() or after sqlite3_shutdown()](https://www.sqlite.org/c3ref/c_config_covering_index_scan.html)

SQLite itself defaults to URI mode being off.  Some distributors enable it by default.  I've chosen to follow SQLite's lead and explicitly having to enable it is the most robust.  

- [ ] Update tips about this URI stuff
- [ ] Ask on SQLite forum for `CONFIG_URI` to be made a runtime parameter

**Comment by dspinellis** [comment]
Thanks! The example works correctly after this configuration. I'm now trying it in the real application.

**Comment by dspinellis** [comment]
As an aside, the semantics of attached files in VFS `memdb` databases (e.g. `"file:/shared-db?vfs=memdb"`) are different from the previously supported named in-memory databases (e.g. `"file:shared-db?mode=memory&cache=shared"`). When a file-based database is attached to an in-memory database with the new VFS `memdb` scheme, updates to the file-based database are not written to disk. I do not consider this to be a bug, but others may find it useful to know this difference.

**Comment by rogerbinns** [comment]
What is happening is more subtle.  Attached databases use the same VFS as the main database unless explicitly specified otherwise.

````
sqlite> .open 'file:/shared?vfs=memdb'
sqlite> attach diskdb as diskdb;`
sqlite> .databases
main: "" r/w
diskdb: "" r/w
sqlite> detach diskdb;
sqlite> attach 'file:diskdb?vfs=unix' as diskdb;
sqlite> .databases
main: "" r/w
diskdb: /space/apsw/sqlite3/diskdb r/w
````

Are you seeing something different than this?

**Comment by rogerbinns** [comment]
The attach docs will [be updated soon](https://sqlite.org/forum/forumpost/ae4612ddeb)

**Comment by dspinellis** [comment]
Indeed, explicitly specifying `vfs=unix` works fine. Thank you!

**Comment by rogerbinns** [comment]
BTW instead of hard coding the VFS name you can use `apsw.vfs_names()[0]` to get the default VFS.

**Comment by rogerbinns** [comment]
@dspinellis it turns out you do not need to do the `SQLITE_CONFIG_URI` dance.  If the database is opened including the `SQLITE_OPEN_URI` flag, then any `ATTACH` on that connection [automatically use URI](https://www.sqlite.org/uri.html#:~:text=If%20URI%20filenames%20are%20recognized%20when%20the%20database%20connection%20is%20originally%20opened%2C%20then%20URI%20filenames%20will%20also%20be%20recognized%20on%20ATTACH%20statements.%20Similarly%2C%20if%20URI%20filenames%20are%20not%20recognized%20when%20the%20database%20connection%20is%20first%20opened%2C%20they%20will%20not%20be%20recognized%20by%20ATTACH.).  (I just did a test to confirm.)

It is probably cleaner too, since you can include or exclude the open flag to clarify if URI support is intended
